## Kaggle House Price Assignment

In [1]:
from IPython.display import HTML
import base64

In [3]:
#Function that takes in a dataframe and creates a text link to
#download it will only work for files <2MB or So

def create_download_link(df,title ="Download CSV File", filename = "data.csv"):
    csv = df.to_csv()
    b64 = base64.b64encode(csv.encode())
    payload = b64.decode()
    html = '<a download ="{filename}" href = "data:text/csv;base64,{payload}"target="_blank">{title}</a>'
    html = html.format(payload = payload, title = title, filename = filename)
    
    return HTML(html)

In [4]:
import numpy as np  #Linear algebra
import pandas as pd # Data Processing , CSV file I/O 
import seaborn as sns
import matplotlib.pyplot as plt
import math
from scipy import stats
from scipy.stats import skew #for some statistics
from scipy.special import boxcox1p
from scipy.stats import boxcox_normmax
from sklearn.metrics import r2_score

%matplotlib inline

In [6]:
import os
print(os.listdir("../datas"))

['sample_submission.csv', 'test.csv', 'train.csv']

In [7]:
#Importing data
train_df = pd.read_csv("../datas/train.csv")
train2 = pd.read_csv("../datas/train.csv")
test_df = pd.read_csv("../datas/test.csv")
test2 = pd.read_csv("../datas/test.csv")

In [10]:
#Attribute info 
print(train_df.shape , test_df.shape)
train_df.head()

(1460, 81) (1459, 80)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [16]:
test_df.tail()
#test_df.kurt()
#test_df.skew()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [53]:
def rstr(df,pred= None):
    obs = df.shape[0]
    types = df.dtypes
    counts = df.apply(lambda x : x.count())
    uniques = df.apply(lambda x : [x.unique()])
    nulls = df.apply(lambda x : x.isnull().sum())
    distincts = df.apply(lambda x:x.unique().shape[0])
    missing_ratio = (df.isnull().sum()/obs)*100
    skewness = df.skew()
    kurtosis = df.kurt()
    print("Data Shape",df.shape)
    
    if pred is None:
        cols = ["types","counts","distincts", 'nulls', 'missing ratio' , 'uniques',"skewness", "kurtosis"]
        str_ = pd.concat([types, counts, distincts, nulls , missing_ratio , uniques , skewness , kurtosis],axis = 1)
    else :
        corr = df.corr()[pred]
        str = pd.concat([types,counts,distincts , nulls , missing_ratio , uniques , skewness , kurtosis,corr],axis=1,sort = False)
        corr_col = 'corr'+pred
        cols = ["types",'counts','distincts', 'nulls','missing ratio','uniques', 'skewness','kurtosis',corr_col]
        
    str_.columns = cols
    
    dtype = str_.types.value_counts()
    print('______________________________________\nData types :\n',str_.types.value_counts())
    print("_______________________________________\n")
    return str_

In [56]:
rstr(train_df,"SalePrice")

Data Shape (1460, 81)

UnboundLocalError: local variable 'str_' referenced before assignment